---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: notejam
  name: notejam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notejam
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notejam
    spec:
      containers:
      - image: container-registry:5000/private-notejam:4  # {"$imagepolicy": "flux-system:private-notejam"}
        name: notejam
        resources: {}
status: {}
