resources:
- namespaces.yaml
- app.yaml

namePrefix: prod-
commonLabels:
  tier: production
  istio-injection: disabled

patchesJson6902:
- path: ./image-pull-secret-patch.yaml
  target:
    kind: Deployment
    name: ".*"
    namespace: ovr-01-production
