# bases:
# - ../../../../.templates/service-mesh
# - ../../../../.templates/ci
# - ../../../../.templates/container-registry

namePrefix: prod
commonLabels:
  tier: production
  istio-injection: disabled

patchesJson6902:
- path: ./image-pull-secret-patch.yaml
  target:
    kind: Deployment
    name: ".*"
    namespace: '.*'
