resources:
- namespaces.yaml
- app.yaml

namespace: ovr-01-production
namePrefix: prod-
commonLabels:
  tier: production
  istio-injection: disabled

patchesJson6902:
- path: ./image-pull-secret-patch.yaml
  target:
    kind: ServiceAccount
    name: default
    namespace: ovr-01-production
