bases:
#- ../../../../.templates/service-mesh
#- ../../../../.templates/ci
- ../../../../.templates/container-registry

# namePrefix: prod-
commonLabels:
  tier: production
  istio-injection: disabled

#patches:
patchesJson6902:
- path: ./image-pull-secret-patch.yaml
  target:
    version: v1
    kind: ServiceAccount
    name: default
