---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: container-registry-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/repository
