apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam-deployment
  labels:
    app: notejam-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notejam-web
      type: production
      priorityclass: critical
  template:
    metadata:
      labels:
        app: notejam-web
        type: production
        priorityclass: critical
    spec:
      containers:
      - name: notejam-web
        image: privatecontainerregitry.azurecr.io/notejam:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/app"
          name: volume
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /app/db.log
          initialDelaySeconds: 5
          periodSeconds: 10
    volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk