apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam-deployment
  labels:
    app: notejam-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notejam-web
      type: production
      priorityclass: critical
  template:
    metadata:
      labels:
        app: notejam-web
        type: production
        priorityclass: critical
    spec:
      containers:
      - name: notejam-web
        image: privatecontainerregitry.azurecr.io/notejam:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080