apiVersion: v1
kind: Service
metadata:
  name: app-service
  annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: notejam-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer