---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: production
  annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: notejam-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: production
spec:
  type: ExternalName
  externalName: <DB-URL> 