bases:
- ../../../base/FE

resources:
- pvc.yaml

namePrefix: FE-

patchesStrategicMerge:
- replica-patch.yaml
- priority-patch.yaml

configMapGenerator:
- name: config.properties
  envs:
  - config.properties

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: notejam
  path: volume-patch.yaml


# In this case tag wil be replaced by digest. For security reasons it is
# recommended to use digest  
images:
   - name: privatecontainerregitry.azurecr.io/notejam
     newTag: 1.0-STAGE
     digest: sha256:24a0c4b4a4c0eb97a1aabb8e29f18e917d05abfe1b7a7c07857230879ce7d3d3
