apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam
spec:
  selector:
    matchLabels:
      app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      priorityClassName: critical
