---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: critical
value: 1000000
globalDefault: No
preemptionPolicy: Never
description: "critical"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: important
value: 800000
globalDefault: Yes
preemptionPolicy: Never
description: "important"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: medium
value: 500000
globalDefault: No
description: "medium"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: normal
value: 300000
globalDefault: No
description: "normal"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low
value: 100000
globalDefault: No
description: "low"