---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: prometheus-repo-pv-1
  spec:
    #storageClassName: manual
    capacity:
      storage: 2Gi
    persistentVolumeReclaimPolicy: Recycle
    accessModes:
    - ReadWriteOnce
    volumeMode: Filesystem
    hostPath:
      path: /tmp/prometheus
---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: prometheus-repo-pv-2
  spec:
    #storageClassName: manual
    capacity:
      storage: 8Gi
    persistentVolumeReclaimPolicy: Recycle
    accessModes:
    - ReadWriteOnce
    volumeMode: Filesystem
    hostPath:
      path: /tmp/prometheus
