---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: critical
handler: runc
overhead:
  podFixed:
    memory: "500Mi"
    cpu: "400m"
---    
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: non-critical
handler: runc
overhead:
  podFixed:
    memory: "120Mi"
    cpu: "250m"