---
- name: Common Configuration
  hosts: all
  #strategy: free
  become: true
  roles:
    - commons

- name: Configuring haproxy
  hosts: loadbalancers
  #strategy: free
  become: true
  roles:
    - loadbalancer

- name: Configuring master and workers
  hosts: masters,workers
  #strategy: free
  become: true
  roles:
    - containerd
    - kubeadm

- name: Configuring master with k8
  hosts: masters
  #strategy: free
  become: true
  remote_user: vagrant
  roles:
    - master
