---
- name: Common Configuration
  hosts: loadbalancers
  strategy: free
  become: true
  roles:
    - commons
    - containerd

- name: Configuring master and workers
  hosts: masters,workers
  strategy: free
  become: true
  roles:
    - kubeadm

- name: Configuring haproxy
  hosts: loadbalancers
  strategy: free
  become: true
  roles:
    - loadbalancer
