---
- name: install kubernetes
  shell: |
    rm -f /home/vagrant/.kube/config
    kubeadm init --apiserver-advertise-address {{ apiserver_advertise_address }} --upload-certs --apiserver-bind-port {{ apiserver_bind_port }} --pod-network-cidr {{ pod_network_cidr }} --control-plane-endpoint {{ control_plane_endpoint }}
    mkdir -p /home/vagrant/.kube
    cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    chown vagrant:vagrant /home/vagrant/.kube/config

- name: configure autocomplete
  shell: |
    echo "source <(kubectl completion bash)" >> /home/vagrant/.bashrc

- name: install weave-network
  shell: |
    kubectl  --kubeconfig /home/vagrant/.kube/config apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

# - name: generating worker join command
#   shell: |
#     kubeadm token create --print-join-command
