---
- name: install kubernetes
  shell: |
    kubeadm init --apiserver-advertise-address 192.168.5.41 --upload-certs --apiserver-bind-port 6443 --pod-network-cidr 10.244.0.0/16 --control-plane-endpoint loadbalancer-1:6443
    mkdir -p /home/vagrant/.kube
    cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    chown vagrant:vagrant /home/vagrant/.kube/config

- name: configure autocomplete
  shell: |
    echo "source <(kubectl completion bash)" >> /home/vagrant/.bashrc

- name: install weave-network
  shell: |
    kubectl  --kubeconfig /home/vagrant/.kube/config apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
