---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 01-production
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 1m0s
  path: ./monitoring-metric-server-dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
