---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ci
  namespace: flux-system
spec:
  dependsOn:
    - name: container-registry
  interval: 1m0s
  path: ./.templates/ci
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
