---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: container-registry
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 1m0s
  path: /.templates/container-registry
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
