---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 01-production
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cd/base/overlays/01-production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
