- name: update DNS
  shell: |
     sed -i -e 's/#DNS=/DNS=8.8.8.8/' /etc/systemd/resolved.conf
     service systemd-resolved restart

- name: allow-bridge-nf-traffic
  shell: |
     modprobe overlay
     modprobe br_netfilter
     sysctl net.bridge.bridge-nf-call-iptables=1
     sysctl net.bridge.bridge-nf-call-ip6tables=1
     sysctl net.ipv4.ip_forward=1

- name: install s/w
  apt:
    name: "{{ item }}"
    state: present
    force: yes
    update_cache: yes
  with_items:
  - wget
  - curl
  - net-tools
  - dnsutils
  - netcat
  - bash-completion
  - tree
