- name: Update DNS
  shell: |
     sed -i -e 's/#DNS=/DNS=8.8.8.8/' /etc/systemd/resolved.conf
     service systemd-resolved restart

- name: allow-bridge-nf-traffic
  shell: |
     modprobe overlay
     modprobe br_netfilter
     sysctl net.bridge.bridge-nf-call-iptables=1

- name: Install s/w
  apt:
    name: "{{ item }}"
    state: present
    force: yes
    update_cache: yes
  with_items:
  - wget

- name: Install Contianerd
  shell: |
     wget https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-amd64.tar.gz
     tar Cxzvf /usr/local containerd-1.6.6-linux-amd64.tar.gz
     mkdir -p /usr/local/lib/systemd/system/
     wget https://raw.githubusercontent.com/containerd/containerd/main/containerd.service --output-document /usr/local/lib/systemd/system/containerd.service
     systemctl daemon-reload
     systemctl enable --now containerd

- name: Install Runc
  shell: |
     wget https://github.com/opencontainers/runc/releases/download/v1.1.3/runc.amd64
     mkdir -p /usr/local/sbin/runc
     install -m 755 runc.amd64 /usr/local/sbin/runc

     mkdir -p /opt/cni/bin
     wget https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
     tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v1.1.1.tgz
