- name: install contianerd
  shell: |
     wget https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-amd64.tar.gz
     tar Cxzvf /usr/local containerd-1.6.6-linux-amd64.tar.gz
     mkdir -p /usr/local/lib/systemd/system/
     wget https://raw.githubusercontent.com/containerd/containerd/main/containerd.service --output-document /usr/local/lib/systemd/system/containerd.service
     systemctl daemon-reload
     systemctl enable --now containerd

- name: install runc
  apt:
    name: runc
    state: present
    force: yes
    update_cache: yes

- name: install cni
  shell: |
     mkdir -p /opt/cni/bin
     wget https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
     tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v1.1.1.tgz

- name: generate default config
  shell: |
     mkdir -p /etc/containerd
     containerd config default > /etc/containerd/config.toml
