apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam
spec:
  replicas: 1 #default
  selector:
    matchLabels:
      app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ["sh","-c","curl db-service"]
      containers:
      - name: notejam-container
        image: privatecontainerregitry.azurecr.io/notejam:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - mountPath: "/app"
          name: pv-volume
        - mountPath: "/app"
          name: app-config-volume
      volumes:
      - name: pv-volume
        emptyDir: {} #configured for local run
      - name: app-config-volume
        configMap:
          name: config.properties