bases:
- ../../../base/FE

resources:
- pvc.yaml

namePrefix: FE-

patchesStrategicMerge:
- replica-patch.yaml
- priority-patch.yaml

configMapGenerator:
- name: config.properties
  envs:
  - config.properties

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: notejam
  path: volume-patch.yaml
