---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-permission
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - psp-permission

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: psp-permission
  name: psp-permission
roleRef:
  kind: ClusterRole
  name: psp-permission
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts:default
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts:production
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
  namespace: production