apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./base/flux-system
resources:
- namespaces.yaml
#- gotk-components.yaml
#- gotk-sync.yaml
#- gotk-sync-service-mesh.yaml
#- gotk-sync-traefik.yaml
