--- 
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata: 
  name: azure-kvname-system-msi
spec: 
  provider: azure
  parameters: 
    cloudName: AzurePublicCloud
    keyvaultName: kv-kms
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    usePodIdentity: "false"
    objects: |
        array:
          - |
            objectName: secret-4
            objectType: secret
    tenantId: "69e8e187-e118-4955-b87e-42e37985b622"