apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dp01
  name: dp01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp01
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dp01
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
