apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
  labels:
    tier: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: StandardSSD_LRS
  resources:
    requests:
      storage: 5Gi