apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testing-acr-connectivity
  name: testing-acr-connectivity
spec:
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - image: privatecontainerregitry.azurecr.io/nginx
    name: testing-acr-connectivity
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
