apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  template:
    metadata:
      labels:
        aadpodidbinding: id-flux-system-pod-identity
    spec:
      containers:
      - name: manager
        env:
        - name: AZURE_AUTH_METHOD
          value: msi
        # - name: AZURE_TENANT_ID
        #   value: "69e8e187-e118-4955-b87e-42e37985b622"
        # - name: AZURE_CLIENT_ID
        #   value: ""
        # - name: AZURE_CLIENT_SECRET
        #   value: key-flux-production
        # envFrom:
        # - secretRef:
        #     name: prod-cluster-repo-public-key