---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  interval: 0h0m10s
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istio-base
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      version: 1.13.4
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 0h0m10s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istiod
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      version: 1.13.4
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 0h0m10s
---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: istio-ingress
#   namespace: istio-ingress
#   labels:
#     app.kubernetes.io/part-of: istio
# spec:
#   releaseName: gateway
#   install:
#     crds: Create
#     remediation:
#       retries: 3
#   upgrade:
#     crds: CreateReplace
#     remediation:
#       retries: 3
#   chart:
#     spec:
#       version: 1.13.4
#       chart: gateway
#       sourceRef:
#         kind: HelmRepository
#         name: istio
#         namespace: istio-system
#   interval: 0h0m10s

 #helm install istiod istio/istiod -n istio-system --wait
