---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system-service-mesh-istio
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./service-mesh
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
