---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 1m0s
  url: https://istio-release.storage.googleapis.com/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istio/base
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1m0s

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istio/gateway
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1m0s
