---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ci-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /vagrant/GitHub/ci-local
